# my.SNOW.yml
#plugin: servicenow.itsm.now
#inventory_hostname_source: host_name
#inventory_hostname_source: cmdb_ci_server
#enhanced: true
#columns:
  #- host_name
  #- name
  #- fqdn
  #- ip_address
  #- os
  #- classification
  #- sys_id
  #- u_compliance
#compose:
  #ip_addr: ip_address
  #compliance: u_compliance if u_compliance != None else default(omit)
  #ansible_host: host_name
#keyed_groups:
  #- key: os
    #separator: ""
  #- key: classification
    #separator: ""
#3groups:
  #compliant_servers: u_compliance != None
plugin: servicenow.itsm.now
enhanced: false
strict: true
table: cmdb_ci_server
columns:
  - name
  - ip_address
  - location
  - location.country
compose:
  street: location
  country: lookup('ansible.builtin.vars', 'location.country')
